package com.istic.projet_spring.Miniprojet.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import com.istic.projet_spring.Miniprojet.model.Purchase;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;

public interface purchaseRepository extends JpaRepository<Purchase, Long>
{

    // Find all purchases by a specific client
    @Query("SELECT p FROM Purchase p WHERE p.client.id = :clientId")
    List<Purchase> findByClientId(@Param("clientId") Long clientId);

    // Count purchases for a specific client
    @Query("SELECT COUNT(p) FROM Purchase p WHERE p.client.id = :clientId")
    Long countPurchasesByClientId(@Param("clientId") Long clientId);

    // Total revenue generated by all purchases
    @Query("SELECT SUM(p.amount) FROM Purchase p")
    Double getTotalRevenue();

    // Total revenue generated by all purchases for a specific client
    @Query("SELECT SUM(p.amount) FROM Purchase p WHERE p.client.id = :clientId")
    Double getTotalRevenueByClientId(@Param("clientId") Long clientId);


    Long countPurchasesByClient(Long clientId) {

    };
}